# Generated by Django 4.1 on 2022-09-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('number_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('number_phone', models.IntegerField()),
                ('id_passport', models.IntegerField()),
                ('e_mail', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hotel', models.CharField(max_length=40)),
                ('number_phone', models.IntegerField()),
                ('adress', models.CharField(max_length=40)),
                ('town', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_hotel', models.CharField(max_length=40)),
                ('active', models.IntegerField()),
                ('squere_room', models.IntegerField()),
                ('vol_room', models.IntegerField()),
                ('vol_bad', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('max_quests', models.IntegerField()),
            ],
        ),
    ]
