# Generated by Django 4.1 on 2022-09-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hosting_quests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_kvartira', models.IntegerField()),
                ('id_guest', models.IntegerField()),
                ('vol_guest', models.IntegerField()),
                ('status', models.CharField(max_length=40)),
                ('e_mail', models.EmailField(max_length=254)),
                ('date_create', models.DateTimeField()),
                ('date_check_in', models.DateTimeField()),
                ('date_check_out', models.DateTimeField()),
                ('notes', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='squere_room',
            new_name='square_room',
        ),
    ]
